name: Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Build
        env:
          SWISSPOST_KEY: ${{ secrets.SWISSPOST_KEY }}
        run: |
          mkdir -p dist
          cp *.png dist/
          sed -e '/popup-version/ s/></>'$GITHUB_SHA'</' -e '/SWISSPOST_KEY/ s/"";/"'$SWISSPOST_KEY'";/' index.html > dist/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: dist
